facebook-application:
  access-token: "EAAGDFS0xZCVABADjw7SfImoaTDZCxI3gXvX8vQ9lLBOcdflBONl6mTO3mVuQbzqyJL7BrsGrYh8EmKyBDbYVZBeAJm5crEWS7RTwqqCMAPmMAsLCOqku1R9Ap15q5zD369zBKMRIXSUxZBcDDW0NfzqoCoMPD3jydrFELhKW29rm3cdRGWGkMzHZCNhK5P0JdiueCPwfLXwZDZD"
  verify-token: "verify123"
  message-url: "https://graph.facebook.com/v2.6/me/messages?access_token="

server:
  port: { $PORT:8080 }