facebook-application:
  access-token: "EAAGDFS0xZCVABAAh9S9JBVcjrvP83TAeIJuDqxWExueIIfMi0F0AiOmPlgfjCIHO7bNbIueRWMTTjQEuSBHjONx3Obeqi8oCLlZCXBBOowoiNRiKPuMYjJXqJy4TXUbDV3c5NVVZBw5O2u8EKACci9Mv94GFZCWorR0bfZA80fl7zcaKi9ZBOvxx38OLoL9ZCheUQU7cpR3uwZDZD"
  verify-token: "verify123"
  message-url: "https://graph.facebook.com/v2.6/me/messages?access_token="

server:
  port: { $PORT:8080 }